apiVersion: v1
kind: Service
metadata:
  name: instant-search
spec:
  #type: ClusterIP
  type: LoadBalancer
  # Uncomment the below line to create a Headless Service
  #clusterIP: None
  selector:
    app: instant-search
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: instant-search
spec:
  selector:
    matchLabels:
      app: instant-search
  replicas: 3
  template:
    metadata:
      labels:
        app: instant-search
    spec:
      containers:
      - name: instant-search
        image: instant-search:latest
        imagePullPolicy: IfNotPresent
